[Rainmeter]
Update=100
;WORKS ONLY IF WEBNOWPLAYER IS INSTALLED
;CONTROLS MAY NOT WORK PROPERLY FOR PLAYERS OTHER THAN SPOTIFY

[Variables]
Color=255,0,0
Highlight=255,255,255

[Background]
Meter=Shape
Shape=Rectangle 0,0,290,400,25 | Fill Color 0,0,0,180 | StrokeWidth 1 | Stroke Color 0,0,0,0

[MeasureStatus]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Status

[MeasureTitle]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Title
UpdateDivider = 5
Substitute="":"N/A"

[MeasureArtist]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Artist
UpdateDivider = 5
Substitute="":"N/A"

[MeasureAlbum]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Album
UpdateDivider = 5
Substitute="":"N/A"

[MeasureAlbumArt]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Cover
DefaultPath=#@#Images\nocover.png
UpdateDivider = 5

[MeasureAlbumArtAddress]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=CoverWebAddress
UpdateDivider = 5

[MeasurePosition]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Position
UpdateDivider = 5
Substitute="":"N/A"

[MeasureDuration]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Duration
UpdateDivider = 5
Substitute="":"N/A"

[MeasureRemaining]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Remaining
UpdateDivider = 5
Substitute="":"N/A"

[MeasureProgress]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Progress
Substitute="":"N/A"

[MeasurePlayPause]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=State
Substitute="0":"Play","1":"Pause","2":"Play","3":"Replay"

[MeasureRepeat]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Repeat
IfCondition=MeasureRepeat = 0
IfTrueAction=[!SetOption MeterRepeat ImageTint "#Color#"][!SetOption MeterRepeat ImageName "#@#Images\repeat.png"]
IfCondition2=MeasureRepeat = 1
IfTrueAction2=[!SetOption MeterRepeat ImageTint "#Highlight#"][!SetOption MeterRepeat ImageName "#@#Images\repeatOne.png"]
IfCondition3=MeasureRepeat = 2
IfTrueAction3=[!SetOption MeterRepeat ImageTint "#Highlight#"][!SetOption MeterRepeat ImageName "#@#Images\repeat.png"]

[MeasureShuffle]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Shuffle
IfCondition=MeasureShuffle = 0
IfTrueAction=[!SetOption MeterShuffle ImageTint "#Color#"]
IfCondition2=MeasureShuffle = 1
IfTrueAction2=[!SetOption MeterShuffle ImageTint "#Highlight#"]

[MeterAlbumArt]
Meter=Image
h=250
w=250
X=20
Y=15
MeasureName=MeasureAlbumArt
PreserveAspectRatio=1

[MeterSongInfo]
Meter=String
y=280
X=60
h=15
w=250
FontColor=#Color#,255
Group=DynamicColors
MeasureName=MeasureTitle
ClipString=2

[MeterArtistInfo]
Meter=String
y=R
X=60
h=15
w=250
FontColor=#Color#,255
Group=DynamicColors
MeasureName=MeasureArtist
ClipString=2

[MeterAlbumInfo]
Meter=String
X=60
y=R
h=15
w=250
FontColor=#Color#,255
Group=DynamicColors
MeasureName=MeasureAlbum
ClipString=2

[MeterPrevious]
Meter=Image
ImageName=#@#Images\previous.png
ImageTint=#Color#
X=20
Y=R
W=48
H=48
Group=DynamicColors
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "Previous"]
AntiAlias=1

[MeterPlayPause]
Meter=Image
ImageName=#@#images\[MeasurePlayPause].png
ImageTint=#Color#
X=R
Y=r
W=48
H=48
Group=DynamicColors
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "PlayPause"]
DynamicVariables=1

[MeterNext]
Meter=Image
ImageName=#@#Images\Next.png
ImageTint=#Color#
X=R
Y=r
W=48
H=48
Group=DynamicColors
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "Next"]
AntiAlias=1

[MeterRepeat]
Meter=Image
ImageTint=#Color#
X=R
Y=r
W=48
H=48
Group=DynamicColors
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "Repeat"]
AntiAlias=1

[MeterShuffle]
Meter=Image
ImageName=#@#Images\shuffle.png
ImageTint=#Color#
X=R
Y=r
W=48
H=48
Group=DynamicColors
LeftMouseUpAction=[!CommandMeasure MeasurePlayPause "Shuffle"]
AntiAlias=1

[MeterPositionInfo]
Meter=String
X=70
y=R
FontColor=#Color#,255
Group=DynamicColors
MeasureName=MeasurePosition

[MeterDurationInfo]
Meter=String
x=R
y=r
FontColor=#Color#,255
Group=DynamicColors
MeasureName=MeasureDuration

[MeterRemainingInfo]
Meter=String
x=R
y=r
FontColor=#Color#,255
Group=DynamicColors
MeasureName=MeasureRemaining

[MeterProgress]
Meter=String
X=R
y=r
Text=%1%
FontColor=#Color#,255
Group=DynamicColors
MeasureName=MeasureProgress
